# Generated by Django 6.0.6 on 2026-10-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderprofile',
            name='vehicle_type',
            field=models.CharField(choices=[('BIKE', 'Bike'), ('CAR', 'Car'), ('VAN', 'Van'), ('TRUCK', 'Truck')], max_length=20),
        ),
    ]
