# Generated by Django 6.0.6 on 2026-10-09 11:20

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0012_remove_deliveryaddress_deliveries__deliver_30402e_idx_and_more'),
        ('riders', '0002_alter_riderprofile_vehicle_type'),
        ('wallet', '0002_alter_wallet_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformCommission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Human-readable label, e.g. 'Default 10%'.", max_length=100, unique=True)),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Commission percentage applied to the gross delivery fee. Range: 0.00 to 100.00.', max_digits=5)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Platform Commission',
                'verbose_name_plural': 'Platform Commissions',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiderEarning',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='The delivery fee charged to the customer. Recorded at the moment of completion.', max_digits=12)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Platform commission deducted from the gross. Snapshotted at the moment of completion from the active PlatformCommission, so later config changes do not affect historical earnings.', max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount credited to the rider. Computed as gross_amount - commission_amount.', max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SETTLED', 'Settled'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='rider_earning', to='deliveries.deliveryassignment')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rider_earnings', to=settings.AUTH_USER_MODEL)),
                ('wallet_transaction', models.OneToOneField(blank=True, help_text='The wallet credit created when this earning settled.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rider_earning', to='wallet.wallettransaction')),
            ],
            options={
                'verbose_name': 'Rider Earning',
                'verbose_name_plural': 'Rider Earnings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='riders_ride_status_7a20f5_idx'), models.Index(fields=['rider', 'status'], name='riders_ride_rider_i_3cc829_idx')],
            },
        ),
    ]
