# Generated by Django 6.0.6 on 2026-08-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0002_riderlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
