# Generated by Django 6.0.6 on 2026-08-22 13:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0003_riderprofile_is_available'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderStatistics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acceptance_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('completion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cancellation_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('completed_deliveries', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='riderlocation',
            name='accuracy',
            field=models.DecimalField(decimal_places=2, default=0, help_text='GPS accuracy in meters.', max_digits=7),
        ),
        migrations.AlterField(
            model_name='riderlocation',
            name='heading',
            field=models.PositiveSmallIntegerField(default=0, help_text='Direction of travel in degrees (0-359).'),
        ),
        migrations.AlterField(
            model_name='riderlocation',
            name='speed',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current rider speed in km/h.', max_digits=7),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='driver_license',
            field=models.ImageField(upload_to='riders/licenses/'),
        ),
        migrations.AddIndex(
            model_name='riderlocation',
            index=models.Index(fields=['last_seen'], name='riders_ride_last_se_912f27_idx'),
        ),
        migrations.AddIndex(
            model_name='riderprofile',
            index=models.Index(fields=['is_online', 'is_available'], name='riders_ride_is_onli_4500fa_idx'),
        ),
        migrations.AddIndex(
            model_name='riderprofile',
            index=models.Index(fields=['verification_status'], name='riders_ride_verific_c8bcbc_idx'),
        ),
        migrations.AddIndex(
            model_name='riderprofile',
            index=models.Index(fields=['vehicle_type'], name='riders_ride_vehicle_2d4400_idx'),
        ),
        migrations.AddField(
            model_name='riderstatistics',
            name='rider',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rider_statistics', to=settings.AUTH_USER_MODEL),
        ),
    ]
