# Generated by Django 6.0.6 on 2026-08-25 17:44

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_productcategory_product_productimage_productvariant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='attributes',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='vendors.product')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductOptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='vendors.productoption')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('alt_text', models.CharField(blank=True, default='', max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vendors.productvariant')),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='productvariant',
            name='productvariantimage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.productvariantimage'),
        ),
        migrations.CreateModel(
            name='ProductVariantOptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('option_value', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variant_links', to='vendors.productoptionvalue')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_option_values', to='vendors.productvariant')),
            ],
            options={
                'ordering': ['option_value__option__sort_order', 'option_value__sort_order', 'option_value__name'],
            },
        ),
        migrations.AddField(
            model_name='productvariant',
            name='option_values',
            field=models.ManyToManyField(blank=True, related_name='variants', through='vendors.ProductVariantOptionValue', to='vendors.productoptionvalue'),
        ),
        migrations.AddIndex(
            model_name='productoption',
            index=models.Index(fields=['product', 'is_active'], name='vendors_pro_product_48119a_idx'),
        ),
        migrations.AddIndex(
            model_name='productoption',
            index=models.Index(fields=['product', 'sort_order'], name='vendors_pro_product_50561d_idx'),
        ),
        migrations.AddConstraint(
            model_name='productoption',
            constraint=models.UniqueConstraint(fields=('product', 'name'), name='unique_product_option_name'),
        ),
        migrations.AddConstraint(
            model_name='productoption',
            constraint=models.UniqueConstraint(fields=('product', 'slug'), name='unique_product_option_slug'),
        ),
        migrations.AddIndex(
            model_name='productoptionvalue',
            index=models.Index(fields=['option', 'is_active'], name='vendors_pro_option__f47670_idx'),
        ),
        migrations.AddIndex(
            model_name='productoptionvalue',
            index=models.Index(fields=['option', 'sort_order'], name='vendors_pro_option__e62348_idx'),
        ),
        migrations.AddConstraint(
            model_name='productoptionvalue',
            constraint=models.UniqueConstraint(fields=('option', 'name'), name='unique_option_value_name'),
        ),
        migrations.AddConstraint(
            model_name='productoptionvalue',
            constraint=models.UniqueConstraint(fields=('option', 'slug'), name='unique_option_value_slug'),
        ),
        migrations.AddIndex(
            model_name='productvariantimage',
            index=models.Index(fields=['variant', 'is_active'], name='vendors_pro_variant_b579c5_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariantimage',
            index=models.Index(fields=['variant', 'is_primary'], name='vendors_pro_variant_2f0a49_idx'),
        ),
        migrations.AddConstraint(
            model_name='productvariantimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('variant',), name='unique_primary_image_per_variant'),
        ),
        migrations.AddIndex(
            model_name='productvariantoptionvalue',
            index=models.Index(fields=['variant'], name='vendors_pro_variant_ff772a_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariantoptionvalue',
            index=models.Index(fields=['option_value'], name='vendors_pro_option__79798c_idx'),
        ),
        migrations.AddConstraint(
            model_name='productvariantoptionvalue',
            constraint=models.UniqueConstraint(fields=('variant', 'option_value'), name='unique_variant_option_value'),
        ),
    ]
