# Generated by Django 6.0.6 on 2026-09-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_productvariant_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='meta_description',
            field=models.CharField(blank=True, default='', max_length=320),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='meta_title',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='unique_category_name_per_parent'),
        ),
    ]
