# Generated by Django 6.0.6 on 2026-09-14 15:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_productcategory_meta_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_options', to='vendors.productcategory')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='vendors_cat_categor_3cc34e_idx'), models.Index(fields=['category', 'sort_order'], name='vendors_cat_categor_02916f_idx')],
                'constraints': [models.UniqueConstraint(fields=('category', 'name'), name='unique_category_option_name'), models.UniqueConstraint(fields=('category', 'slug'), name='unique_category_option_slug')],
            },
        ),
    ]
