# Generated by Django 6.0.6 on 2026-09-17 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_add_category_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='productvariantimage',
        ),
    ]
