# Generated by Django 6.0.6 on 2026-10-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_remove_productvariant_productvariantimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariantoptionvalue',
            options={},
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('name',), name='unique_root_category_name'),
        ),
    ]
