# Generated by Django 6.0.6 on 2026-10-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_vendorstore_state_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_perishable',
            field=models.BooleanField(db_index=True, default=False, help_text='Perishable items are not refunded when a vendor cannot fulfill an order.'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_perishable'], name='vendors_pro_is_peri_90b7f6_idx'),
        ),
    ]
