# Generated by Django 6.0.6 on 2026-10-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('DELIVERY', 'Delivery'), ('PAYMENT', 'Payment'), ('WALLET', 'Wallet'), ('SYSTEM', 'System'), ('PROMOTION', 'Promotion'), ('DELIVERY_OFFER', 'Delivery Offer')], default='SYSTEM', max_length=20),
        ),
    ]
