# Generated by Django 6.0.6 on 2026-08-28 15:48

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('ready_for_dispatch', 'Ready for Dispatch'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, default='pending', max_length=30)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], db_index=True, default='pending', max_length=30)),
                ('payment_method', models.CharField(blank=True, choices=[('wallet', 'Wallet'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash')], default='', max_length=30)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('service_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('insurance_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('customer_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address_type', models.CharField(choices=[('SHIPPING', 'Shipping'), ('BILLING', 'Billing')], default='SHIPPING', max_length=20)),
                ('recipient_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=30)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('landmark', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='order.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order_addresses',
            },
        ),
        migrations.CreateModel(
            name='OrderFulfillment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=255)),
                ('store_address_line_1', models.CharField(max_length=255)),
                ('store_address_line_2', models.CharField(blank=True, default='', max_length=255)),
                ('store_city', models.CharField(max_length=100)),
                ('store_state', models.CharField(max_length=100)),
                ('store_country', models.CharField(default='Nigeria', max_length=100)),
                ('store_postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('store_latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('store_longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('packing', 'Packing'), ('ready_for_dispatch', 'Ready for Dispatch'), ('dispatched', 'Dispatched'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, default='pending', max_length=30)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('service_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('insurance_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('vendor_note', models.TextField(blank=True, default='')),
                ('preparation_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processing_at', models.DateTimeField(blank=True, null=True)),
                ('packing_at', models.DateTimeField(blank=True, null=True)),
                ('ready_for_dispatch_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('out_for_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fulfillments', to='order.order')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_fulfillments', to='vendors.vendorstore')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('product_sku', models.CharField(blank=True, default='', max_length=100)),
                ('variant_name', models.CharField(blank=True, default='', max_length=255)),
                ('variant_sku', models.CharField(blank=True, default='', max_length=100)),
                ('option_summary', models.CharField(blank=True, default='', max_length=1000)),
                ('store_name', models.CharField(max_length=255)),
                ('store_address_line_1', models.CharField(max_length=255)),
                ('store_address_line_2', models.CharField(blank=True, default='', max_length=255)),
                ('store_city', models.CharField(max_length=100)),
                ('store_state', models.CharField(max_length=100)),
                ('store_country', models.CharField(default='Nigeria', max_length=100)),
                ('store_postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('store_latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('store_longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fulfillment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='order.orderfulfillment')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='vendors.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='vendors.vendorstore')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='vendors.productvariant')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_method', models.CharField(choices=[('CARD', 'Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('USSD', 'USSD'), ('WALLET', 'Wallet'), ('CASH', 'Cash')], max_length=30)),
                ('provider', models.CharField(choices=[('PAYSTACK', 'Paystack'), ('FLUTTERWAVE', 'Flutterwave'), ('WALLET', 'Wallet'), ('CASH', 'Cash')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially Refunded')], default='PENDING', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('provider_reference', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='order.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order_payments',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('package_number', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('tracking_number', models.CharField(db_index=True, editable=False, max_length=100, unique=True)),
                ('package_type', models.CharField(choices=[('envelope', 'Envelope'), ('small_box', 'Small Box'), ('medium_box', 'Medium Box'), ('large_box', 'Large Box'), ('custom', 'Custom')], default='custom', max_length=30)),
                ('status', models.CharField(choices=[('created', 'Created'), ('packing', 'Packing'), ('packed', 'Packed'), ('ready_for_pickup', 'Ready for Pickup'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('lost', 'Lost'), ('damaged', 'Damaged')], db_index=True, default='created', max_length=30)),
                ('weight', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Weight in kilograms.', max_digits=10)),
                ('length', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Length in centimeters.', max_digits=10)),
                ('width', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Width in centimeters.', max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Height in centimeters.', max_digits=10)),
                ('is_fragile', models.BooleanField(default=False)),
                ('requires_special_handling', models.BooleanField(default=False)),
                ('special_handling_note', models.TextField(blank=True, default='')),
                ('declared_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('packaging_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('packed_at', models.DateTimeField(blank=True, null=True)),
                ('ready_for_pickup_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('in_transit_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('fulfillment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='order.orderfulfillment')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', '-created_at'], name='order_order_custome_a2521b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='order_order_status_f574c5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status', '-created_at'], name='order_order_payment_6e5590_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', 'status'], name='order_order_custome_d581fb_idx'),
        ),
        migrations.AddIndex(
            model_name='orderaddress',
            index=models.Index(fields=['order'], name='order_address_order_idx'),
        ),
        migrations.AddIndex(
            model_name='orderaddress',
            index=models.Index(fields=['user'], name='order_address_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderaddress',
            constraint=models.UniqueConstraint(fields=('order', 'address_type'), name='unique_order_address_type'),
        ),
        migrations.AddIndex(
            model_name='orderfulfillment',
            index=models.Index(fields=['order'], name='order_order_order_i_c64422_idx'),
        ),
        migrations.AddIndex(
            model_name='orderfulfillment',
            index=models.Index(fields=['store'], name='order_order_store_i_9e7f88_idx'),
        ),
        migrations.AddIndex(
            model_name='orderfulfillment',
            index=models.Index(fields=['status'], name='order_order_status_42760c_idx'),
        ),
        migrations.AddIndex(
            model_name='orderfulfillment',
            index=models.Index(fields=['order', 'status'], name='order_order_order_i_1528ba_idx'),
        ),
        migrations.AddIndex(
            model_name='orderfulfillment',
            index=models.Index(fields=['store', 'status'], name='order_order_store_i_fa60ab_idx'),
        ),
        migrations.AddIndex(
            model_name='orderfulfillment',
            index=models.Index(fields=['created_at'], name='order_order_created_188260_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderfulfillment',
            constraint=models.UniqueConstraint(fields=('order', 'store'), name='unique_order_store_fulfillment'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='order_order_order_i_854de1_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['fulfillment'], name='order_order_fulfill_f959a6_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product'], name='order_order_product_ed1645_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['variant'], name='order_order_variant_e88861_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['store'], name='order_order_store_i_e6bcf9_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'store'], name='order_order_order_i_44a33b_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'fulfillment'], name='order_order_order_i_2bbca9_idx'),
        ),
        migrations.AddIndex(
            model_name='orderpayment',
            index=models.Index(fields=['order'], name='order_payment_order_idx'),
        ),
        migrations.AddIndex(
            model_name='orderpayment',
            index=models.Index(fields=['user'], name='order_payment_user_idx'),
        ),
        migrations.AddIndex(
            model_name='orderpayment',
            index=models.Index(fields=['status'], name='order_payment_status_idx'),
        ),
        migrations.AddIndex(
            model_name='orderpayment',
            index=models.Index(fields=['provider', 'provider_reference'], name='order_payment_provider_ref_idx'),
        ),
        migrations.AddIndex(
            model_name='orderpayment',
            index=models.Index(fields=['created_at'], name='order_payment_created_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['fulfillment'], name='package_fulfillment_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['status'], name='package_status_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['fulfillment', 'status'], name='package_fulfillment_status_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['tracking_number'], name='package_tracking_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['created_at'], name='package_created_idx'),
        ),
    ]
