# Generated by Django 6.0.6 on 2026-08-29 16:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='package_items', to='order.orderitem')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.package')),
            ],
            options={
                'indexes': [models.Index(fields=['package'], name='order_packa_package_7ceda1_idx'), models.Index(fields=['order_item'], name='order_packa_order_i_5a7a4e_idx')],
                'constraints': [models.UniqueConstraint(fields=('package', 'order_item'), name='unique_package_order_item')],
            },
        ),
    ]
