# Generated by Django 6.0.6 on 2026-09-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_packageitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfulfillment',
            name='store_contact_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='orderfulfillment',
            name='store_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
