# Generated by Django 6.0.6 on 2026-10-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderfulfillment_store_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfulfillment',
            name='delivery_type',
            field=models.CharField(choices=[('INSTANT', 'Instant'), ('SCHEDULED', 'Scheduled')], default='INSTANT', help_text='Delivery type for the associated Delivery.', max_length=20),
        ),
        migrations.AddField(
            model_name='orderfulfillment',
            name='package_size',
            field=models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large')], default='SMALL', help_text='Package size bucket used for delivery pricing.', max_length=10),
        ),
        migrations.AddField(
            model_name='orderfulfillment',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text='Required when delivery_type is SCHEDULED.', null=True),
        ),
        migrations.AddField(
            model_name='orderfulfillment',
            name='vehicle_type',
            field=models.CharField(blank=True, help_text='Requested vehicle class. Null means the dispatcher decides.', max_length=20, null=True),
        ),
    ]
