# Generated by Django 6.0.6 on 2026-10-06 19:28

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_orderfulfillment_delivery_type_and_more'),
        ('vendors', '0008_product_is_perishable_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='orderitem',
            name='order_order_order_i_854de1_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='order_order_fulfill_f959a6_idx',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fulfillment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('FULFILLED', 'Fulfilled'), ('UNAVAILABLE', 'Unavailable')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_perishable',
            field=models.BooleanField(db_index=True, default=False, help_text='Snapshot of Product.is_perishable at checkout. Perishable items are excluded from refunds.'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unavailable_reason',
            field=models.TextField(blank=True, default='', help_text='Populated when fulfillment_status is UNAVAILABLE.'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='store_latitude',
            field=models.DecimalField(decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='store_longitude',
            field=models.DecimalField(decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))]),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['fulfillment', 'fulfillment_status', 'is_perishable'], name='order_order_fulfill_804bb5_idx'),
        ),
    ]
