# Generated by Django 6.0.6 on 2026-10-07 18:19

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_orderitem_order_order_order_i_854de1_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='orderfulfillment',
            name='order_order_order_i_c64422_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderfulfillment',
            name='order_order_store_i_9e7f88_idx',
        ),
        migrations.RemoveIndex(
            model_name='package',
            name='package_fulfillment_idx',
        ),
        migrations.RemoveIndex(
            model_name='package',
            name='package_tracking_idx',
        ),
        migrations.RemoveIndex(
            model_name='packageitem',
            name='order_packa_package_7ceda1_idx',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_otp',
            field=models.CharField(blank=True, db_index=True, default='', max_length=6),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_otp_attempts',
            field=models.PositiveSmallIntegerField(default=0, help_text='Failed verification attempts. Locks after 5.'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_otp_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_otp_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderfulfillment',
            name='delivery_address_line_1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='orderfulfillment',
            name='delivery_address_line_2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='orderfulfillment',
            name='delivery_city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='orderfulfillment',
            name='delivery_contact_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='orderfulfillment',
            name='delivery_contact_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='orderfulfillment',
            name='delivery_country',
            field=models.CharField(blank=True, default='Nigeria', max_length=100),
        ),
        migrations.AddField(
            model_name='orderfulfillment',
            name='delivery_instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='orderfulfillment',
            name='delivery_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderfulfillment',
            name='delivery_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderfulfillment',
            name='delivery_otp',
            field=models.CharField(blank=True, db_index=True, default='', help_text='6-digit code the customer shares with the rider to confirm handover.', max_length=6),
        ),
        migrations.AddField(
            model_name='orderfulfillment',
            name='delivery_otp_attempts',
            field=models.PositiveSmallIntegerField(default=0, help_text='Failed verification attempts. Locks after 5.'),
        ),
        migrations.AddField(
            model_name='orderfulfillment',
            name='delivery_otp_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderfulfillment',
            name='delivery_otp_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderfulfillment',
            name='delivery_postal_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='orderfulfillment',
            name='delivery_state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='orderfulfillment',
            name='store_pickup_instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='orderfulfillment',
            name='store_preparation_time_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit_weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Unit weight in kilograms, snapshotted at checkout. Null when the source catalog item had no weight.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='address_line_2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='landmark',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))]),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))]),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderfulfillment',
            name='store_contact_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='orderfulfillment',
            name='store_contact_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderfulfillment',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('BIKE', 'Bike'), ('CAR', 'Car'), ('VAN', 'Van'), ('TRUCK', 'Truck')], help_text='Requested vehicle class. Null means the dispatcher decides.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='store_latitude',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='store_longitude',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='failure_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially Refunded')], db_index=True, default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='package',
            name='declared_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='package',
            name='height',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Height in centimeters.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='package',
            name='length',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Length in centimeters.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='package',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Weight in kilograms.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))]),
        ),
        migrations.AlterField(
            model_name='package',
            name='width',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Width in centimeters.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='packageitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
