# Generated by Django 6.0.6 on 2026-10-08 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_orderfulfillment_order_order_order_i_c64422_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_otp',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_otp_attempts',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_otp_generated_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_otp_verified_at',
        ),
    ]
