# Generated by Django 6.0.6 on 2026-08-26 20:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchConfiguration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('dispatch_strategy', models.CharField(choices=[('BALANCED', 'Balanced'), ('NEAREST', 'Nearest Rider'), ('PERFORMANCE', 'Performance Based'), ('VENDOR_PRIORITY', 'Vendor Priority'), ('CUSTOMER_PRIORITY', 'Customer Priority'), ('FAIR_DISTRIBUTION', 'Fair Distribution'), ('EXPRESS', 'Express Delivery')], default='BALANCED', help_text='Determines how riders are ranked during dispatch.', max_length=30)),
                ('initial_search_radius_km', models.DecimalField(decimal_places=2, default=3, max_digits=5)),
                ('maximum_search_radius_km', models.DecimalField(decimal_places=2, default=15, max_digits=5)),
                ('search_radius_increment_km', models.DecimalField(decimal_places=2, default=2, max_digits=5)),
                ('rider_response_timeout_seconds', models.PositiveIntegerField(default=30)),
                ('max_assignment_attempts', models.PositiveSmallIntegerField(default=5)),
                ('auto_redispatch', models.BooleanField(default=True)),
                ('minimum_rider_rating', models.DecimalField(decimal_places=2, default=3.5, max_digits=3)),
                ('maximum_active_deliveries', models.PositiveSmallIntegerField(default=2)),
                ('rating_weight', models.DecimalField(decimal_places=2, default=10, max_digits=6)),
                ('distance_weight', models.DecimalField(decimal_places=2, default=2, max_digits=6)),
                ('workload_weight', models.DecimalField(decimal_places=2, default=5, max_digits=6)),
                ('acceptance_rate_weight', models.DecimalField(decimal_places=2, default=4, max_digits=6)),
                ('completion_rate_weight', models.DecimalField(decimal_places=2, default=3, max_digits=6)),
                ('cancellation_weight', models.DecimalField(decimal_places=2, default=8, help_text='Penalty applied to riders with higher cancellation rates.', max_digits=6)),
                ('experience_weight', models.DecimalField(decimal_places=2, default=2, max_digits=6)),
                ('offer_batch_size', models.PositiveSmallIntegerField(default=1, help_text='Number of riders offered a delivery simultaneously.')),
                ('allow_scheduled_dispatch', models.BooleanField(default=True)),
                ('dispatch_before_pickup_minutes', models.PositiveIntegerField(default=15)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PricingConfiguration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Example: Lagos Default Pricing', max_length=100, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_price', models.DecimalField(decimal_places=2, default=1000, max_digits=10)),
                ('price_per_km', models.DecimalField(decimal_places=2, default=250, max_digits=10)),
                ('service_fee', models.DecimalField(decimal_places=2, default=300, max_digits=10)),
                ('insurance_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0100'), help_text='Decimal percentage (0.01 = 1%)', max_digits=5)),
                ('small_package_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('medium_package_fee', models.DecimalField(decimal_places=2, default=300, max_digits=10)),
                ('large_package_fee', models.DecimalField(decimal_places=2, default=700, max_digits=10)),
                ('bike_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('car_multiplier', models.DecimalField(decimal_places=2, default=1.35, max_digits=5)),
                ('van_multiplier', models.DecimalField(decimal_places=2, default=1.8, max_digits=5)),
                ('truck_multiplier', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('enable_surge', models.BooleanField(default=False)),
                ('surge_multiplier', models.DecimalField(decimal_places=2, default=1.5, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('pickup_store_name', models.CharField(blank=True, max_length=255)),
                ('delivery_type', models.CharField(choices=[('INSTANT', 'Instant'), ('SCHEDULED', 'Scheduled')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('WAITING_FOR_RIDER', 'Waiting for Rider'), ('RIDER_ASSIGNED', 'Rider Assigned'), ('RIDER_ACCEPTED', 'Rider Accepted'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=30)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=20)),
                ('pickup_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pickup_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pickup_address', models.TextField()),
                ('destination_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destination_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destination_address', models.TextField()),
                ('vehicle_type', models.CharField(blank=True, choices=[('BIKE', 'Bike'), ('CAR', 'Car'), ('VAN', 'Van')], max_length=20, null=True)),
                ('package_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('package_size', models.CharField(blank=True, max_length=30)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actual_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('distance_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('weight_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('surge_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('insurance_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to=settings.AUTH_USER_MODEL)),
                ('pickup_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='vendors.vendorstore')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='vendors.vendorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address_type', models.CharField(choices=[('PICKUP', 'Pickup'), ('DELIVERY', 'Delivery')], max_length=20)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('landmark', models.CharField(blank=True, max_length=255)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='deliveries.delivery')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('ACCEPTED', 'Accepted'), ('EN_ROUTE_PICKUP', 'En Route to Pickup'), ('ARRIVED_PICKUP', 'Arrived at Pickup'), ('PICKED_UP', 'Picked Up'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('ARRIVED_DESTINATION', 'Arrived at Destination'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(help_text='Admin or system that assigned the rider.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deliveries', to=settings.AUTH_USER_MODEL)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='deliveries.delivery')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('variant_name', models.CharField(blank=True, max_length=255)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('unit_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='deliveries.delivery')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_items', to='vendors.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_items', to='vendors.vendorstore')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_items', to='vendors.productvariant')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryOffer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('search_radius', models.DecimalField(decimal_places=2, max_digits=6)),
                ('offered_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('rejection_reason', models.TextField(blank=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='deliveries.delivery')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-offered_at',),
            },
        ),
        migrations.CreateModel(
            name='DeliveryTimeline',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('CREATED', 'Created'), ('SEARCHING_RIDERS', 'Searching Riders'), ('OFFER_SENT', 'Offer Sent'), ('OFFER_ACCEPTED', 'Offer Accepted'), ('OFFER_REJECTED', 'Offer Rejected'), ('OFFER_EXPIRED', 'Offer Expired'), ('ASSIGNED', 'Assigned'), ('RIDER_ARRIVED', 'Rider Arrived'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_timeline_events', to=settings.AUTH_USER_MODEL)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='deliveries.delivery')),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='DispatchHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('DELIVERY_CREATED', 'Delivery Created'), ('DISPATCH_STARTED', 'Dispatch Started'), ('OFFER_CREATED', 'Offer Created'), ('OFFER_ACCEPTED', 'Offer Accepted'), ('OFFER_REJECTED', 'Offer Rejected'), ('OFFER_EXPIRED', 'Offer Expired'), ('OFFER_CANCELLED', 'Offer Cancelled'), ('RIDER_ASSIGNED', 'Rider Assigned'), ('ASSIGNMENT_ACCEPTED', 'Assignment Accepted'), ('PICKUP_STARTED', 'Pickup Started'), ('ARRIVED_PICKUP', 'Arrived Pickup'), ('PICKUP_COMPLETED', 'Pickup Completed'), ('DELIVERY_STARTED', 'Delivery Started'), ('ARRIVED_DESTINATION', 'Arrived Destination'), ('DELIVERY_COMPLETED', 'Delivery Completed'), ('ASSIGNMENT_CANCELLED', 'Assignment Cancelled'), ('ASSIGNMENT_REASSIGNED', 'Assignment Reassigned'), ('DISPATCH_FAILED', 'Dispatch Failed')], max_length=50)),
                ('status', models.CharField(blank=True, default='', max_length=50)),
                ('message', models.TextField(blank=True, default='')),
                ('reason', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_history', to='deliveries.deliveryassignment')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_history', to='deliveries.delivery')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_history', to='deliveries.deliveryoffer')),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=255)),
                ('package_category', models.CharField(choices=[('DOCUMENT', 'Document'), ('FOOD', 'Food'), ('ELECTRONICS', 'Electronics'), ('CLOTHING', 'Clothing'), ('MEDICAL', 'Medical'), ('OTHER', 'Other')], max_length=30)),
                ('package_size', models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large')], max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('fragile', models.BooleanField(default=False)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='packages/')),
                ('description', models.TextField(blank=True)),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='package', to='deliveries.delivery')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['status'], name='deliveries__status_bdfe1b_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['payment_status'], name='deliveries__payment_570175_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['vendor'], name='deliveries__vendor__a7b338_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['customer'], name='deliveries__custome_2e03f8_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['pickup_store'], name='deliveries__pickup__1f8af0_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryassignment',
            index=models.Index(fields=['delivery', 'status'], name='deliveries__deliver_08f50c_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryassignment',
            index=models.Index(fields=['rider', 'status'], name='deliveries__rider_i_a07fbe_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryassignment',
            index=models.Index(fields=['status'], name='deliveries__status_648496_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryassignment',
            index=models.Index(fields=['assigned_at'], name='deliveries__assigne_e971eb_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryassignment',
            index=models.Index(fields=['is_active'], name='deliveries__is_acti_b50520_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryitem',
            index=models.Index(fields=['delivery'], name='deliveries__deliver_78ca5a_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryitem',
            index=models.Index(fields=['product'], name='deliveries__product_73fc9b_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryitem',
            index=models.Index(fields=['variant'], name='deliveries__variant_041ee5_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryitem',
            index=models.Index(fields=['store'], name='deliveries__store_i_c32f44_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryoffer',
            index=models.Index(fields=['delivery', 'status'], name='deliveries__deliver_56f416_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryoffer',
            index=models.Index(fields=['rider', 'status'], name='deliveries__rider_i_96c255_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryoffer',
            index=models.Index(fields=['expires_at'], name='deliveries__expires_b7811a_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverytimeline',
            index=models.Index(fields=['delivery', 'occurred_at'], name='deliveries__deliver_eaa39f_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchhistory',
            index=models.Index(fields=['delivery', 'created_at'], name='deliveries__deliver_8ff19d_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchhistory',
            index=models.Index(fields=['event_type', 'created_at'], name='deliveries__event_t_9cd63b_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchhistory',
            index=models.Index(fields=['rider', 'created_at'], name='deliveries__rider_i_cc91bc_idx'),
        ),
    ]
