# Generated by Django 6.0.6 on 2026-08-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='delivery',
        ),
        migrations.AlterModelOptions(
            name='deliveryaddress',
            options={'ordering': ['address_type']},
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='destination_address',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='destination_latitude',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='destination_longitude',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='package_size',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='package_weight',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='pickup_address',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='pickup_latitude',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='pickup_longitude',
        ),
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='address',
        ),
        migrations.AddField(
            model_name='delivery',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='currency',
            field=models.CharField(default='NGN', max_length=3),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='estimated_duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
