# Generated by Django 6.0.6 on 2026-08-28 15:48

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_remove_package_delivery_and_more'),
        ('order', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='fulfillment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery', to='order.orderfulfillment'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='in_transit_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='package_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='delivery',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='rider_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='rider_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='total_package_weight',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Total package weight in kilograms.', max_digits=10),
        ),
        migrations.AddField(
            model_name='delivery',
            name='waiting_for_rider_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='address_line_1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='address_line_2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='country',
            field=models.CharField(default='Nigeria', max_length=100),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='arrived_destination_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='arrived_pickup_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='en_route_pickup_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='failure_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='out_for_delivery_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='estimated_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='pickup_store_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='tracking_number',
            field=models.CharField(db_index=True, editable=False, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='vendors.vendorprofile'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='contact_phone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='landmark',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='deliveryassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='Admin or system user that created the assignment. Null means system-generated.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_delivery_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deliveryassignment',
            name='cancellation_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='deliveryassignment',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='deliveries.delivery'),
        ),
        migrations.AlterField(
            model_name='deliveryassignment',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='deliveryassignment',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='deliveryassignment',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='deliveryassignment',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deliveryassignment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('ACCEPTED', 'Accepted'), ('EN_ROUTE_PICKUP', 'En Route to Pickup'), ('ARRIVED_PICKUP', 'Arrived at Pickup'), ('PICKED_UP', 'Picked Up'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('ARRIVED_DESTINATION', 'Arrived at Destination'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=30),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['scheduled_at'], name='deliveries__schedul_b5bb8f_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['status', 'scheduled_at'], name='deliveries__status_2d2b3f_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['vendor', 'status'], name='deliveries__vendor__d15aaa_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['pickup_store', 'status'], name='deliveries__pickup__d6c458_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryaddress',
            index=models.Index(fields=['delivery'], name='deliveries__deliver_30402e_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryaddress',
            index=models.Index(fields=['address_type'], name='deliveries__address_c97941_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryaddress',
            index=models.Index(fields=['delivery', 'address_type'], name='deliveries__deliver_c5b52d_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryaddress',
            index=models.Index(fields=['contact_phone'], name='deliveries__contact_8217e5_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryassignment',
            index=models.Index(fields=['rider', 'is_active'], name='deliveries__rider_i_842e2c_idx'),
        ),
        migrations.AddConstraint(
            model_name='deliveryaddress',
            constraint=models.UniqueConstraint(fields=('delivery', 'address_type'), name='unique_delivery_address_type'),
        ),
        migrations.AddConstraint(
            model_name='deliveryassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('delivery',), name='unique_active_delivery_assignment'),
        ),
        migrations.DeleteModel(
            name='Package',
        ),
    ]
