# Generated by Django 6.0.6 on 2026-07-16 23:41

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_delivery_base_price_delivery_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('initial_search_radius_km', models.DecimalField(decimal_places=2, default=3, max_digits=5)),
                ('maximum_search_radius_km', models.DecimalField(decimal_places=2, default=15, max_digits=5)),
                ('search_radius_increment_km', models.DecimalField(decimal_places=2, default=2, max_digits=5)),
                ('rider_response_timeout_seconds', models.PositiveIntegerField(default=30)),
                ('max_assignment_attempts', models.PositiveSmallIntegerField(default=5)),
                ('auto_redispatch', models.BooleanField(default=True)),
                ('minimum_rider_rating', models.DecimalField(decimal_places=2, default=3.5, max_digits=3)),
                ('maximum_active_deliveries', models.PositiveSmallIntegerField(default=2)),
                ('allow_scheduled_dispatch', models.BooleanField(default=True)),
                ('dispatch_before_pickup_minutes', models.PositiveIntegerField(default=15)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PricingConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Example: Lagos Default Pricing', max_length=100, unique=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=1000, max_digits=10)),
                ('price_per_km', models.DecimalField(decimal_places=2, default=250, max_digits=10)),
                ('service_fee', models.DecimalField(decimal_places=2, default=300, max_digits=10)),
                ('insurance_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0100'), help_text='Decimal percentage (0.01 = 1%)', max_digits=5)),
                ('small_package_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('medium_package_fee', models.DecimalField(decimal_places=2, default=300, max_digits=10)),
                ('large_package_fee', models.DecimalField(decimal_places=2, default=700, max_digits=10)),
                ('bike_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('car_multiplier', models.DecimalField(decimal_places=2, default=1.35, max_digits=5)),
                ('van_multiplier', models.DecimalField(decimal_places=2, default=1.8, max_digits=5)),
                ('truck_multiplier', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('enable_surge', models.BooleanField(default=False)),
                ('surge_multiplier', models.DecimalField(decimal_places=2, default=1.5, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
