# Generated by Django 6.0.6 on 2026-07-17 00:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0004_dispatchconfiguration_pricingconfiguration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('offered_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('rejection_reason', models.TextField(blank=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='deliveries.delivery')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-offered_at',),
                'indexes': [models.Index(fields=['delivery', 'status'], name='deliveries__deliver_56f416_idx'), models.Index(fields=['rider', 'status'], name='deliveries__rider_i_96c255_idx'), models.Index(fields=['expires_at'], name='deliveries__expires_b7811a_idx')],
            },
        ),
    ]
