# Generated by Django 6.0.6 on 2026-08-28 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0004_alter_delivery_pickup_store_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispatchconfiguration',
            old_name='max_assignment_attempts',
            new_name='max_rider_assignments',
        ),
    ]
