# Generated by Django 6.0.6 on 2026-08-03 19:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0005_deliveryoffer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryoffer',
            name='search_radius',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dispatchconfiguration',
            name='acceptance_rate_weight',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=6),
        ),
        migrations.AddField(
            model_name='dispatchconfiguration',
            name='cancellation_rate_weight',
            field=models.DecimalField(decimal_places=2, default=8, max_digits=6),
        ),
        migrations.AddField(
            model_name='dispatchconfiguration',
            name='completion_rate_weight',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=6),
        ),
        migrations.AddField(
            model_name='dispatchconfiguration',
            name='dispatch_strategy',
            field=models.CharField(choices=[('BALANCED', 'Balanced'), ('NEAREST', 'Nearest Rider'), ('PERFORMANCE', 'Performance Based'), ('VENDOR_PRIORITY', 'Vendor Priority'), ('CUSTOMER_PRIORITY', 'Customer Priority'), ('FAIR_DISTRIBUTION', 'Fair Distribution'), ('EXPRESS', 'Express Delivery')], default='BALANCED', max_length=30),
        ),
        migrations.AddField(
            model_name='dispatchconfiguration',
            name='distance_weight',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=6),
        ),
        migrations.AddField(
            model_name='dispatchconfiguration',
            name='experience_weight',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=6),
        ),
        migrations.AddField(
            model_name='dispatchconfiguration',
            name='offer_batch_size',
            field=models.PositiveSmallIntegerField(default=1, help_text='Number of riders offered a delivery simultaneously.'),
        ),
        migrations.AddField(
            model_name='dispatchconfiguration',
            name='rating_weight',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=6),
        ),
        migrations.AddField(
            model_name='dispatchconfiguration',
            name='workload_weight',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=6),
        ),
        migrations.AlterField(
            model_name='deliveryoffer',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='DeliveryTimeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(choices=[('CREATED', 'Created'), ('SEARCHING_RIDERS', 'Searching Riders'), ('OFFER_SENT', 'Offer Sent'), ('OFFER_ACCEPTED', 'Offer Accepted'), ('OFFER_REJECTED', 'Offer Rejected'), ('OFFER_EXPIRED', 'Offer Expired'), ('ASSIGNED', 'Assigned'), ('RIDER_ARRIVED', 'Rider Arrived'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_timeline_events', to=settings.AUTH_USER_MODEL)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='deliveries.delivery')),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['delivery', 'occurred_at'], name='deliveries__deliver_eaa39f_idx')],
            },
        ),
    ]
