# Generated by Django 6.0.6 on 2026-08-21 20:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0006_deliveryoffer_search_radius_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('DELIVERY_CREATED', 'Delivery Created'), ('DISPATCH_STARTED', 'Dispatch Started'), ('OFFER_CREATED', 'Offer Created'), ('OFFER_ACCEPTED', 'Offer Accepted'), ('OFFER_REJECTED', 'Offer Rejected'), ('OFFER_EXPIRED', 'Offer Expired'), ('OFFER_CANCELLED', 'Offer Cancelled'), ('RIDER_ASSIGNED', 'Rider Assigned'), ('ASSIGNMENT_ACCEPTED', 'Assignment Accepted'), ('PICKUP_STARTED', 'Pickup Started'), ('ARRIVED_PICKUP', 'Arrived Pickup'), ('PICKUP_COMPLETED', 'Pickup Completed'), ('DELIVERY_STARTED', 'Delivery Started'), ('ARRIVED_DESTINATION', 'Arrived Destination'), ('DELIVERY_COMPLETED', 'Delivery Completed'), ('ASSIGNMENT_CANCELLED', 'Assignment Cancelled'), ('ASSIGNMENT_REASSIGNED', 'Assignment Reassigned'), ('DISPATCH_FAILED', 'Dispatch Failed')], max_length=50)),
                ('status', models.CharField(blank=True, default='', max_length=50)),
                ('message', models.TextField(blank=True, default='')),
                ('reason', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_history', to='deliveries.deliveryassignment')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_history', to='deliveries.delivery')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_history', to='deliveries.deliveryoffer')),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['delivery', 'created_at'], name='deliveries__deliver_8ff19d_idx'), models.Index(fields=['event_type', 'created_at'], name='deliveries__event_t_9cd63b_idx'), models.Index(fields=['rider', 'created_at'], name='deliveries__rider_i_cc91bc_idx')],
            },
        ),
    ]
