# Generated by Django 6.0.6 on 2026-08-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0006_alter_dispatchconfiguration_max_rider_assignments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchconfiguration',
            name='max_rider_assignments',
            field=models.PositiveSmallIntegerField(default=10, help_text='Maximum number of rider assignments allowed for a delivery. Use 0 for unlimited.'),
        ),
    ]
