# Generated by Django 6.0.6 on 2026-08-22 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0007_dispatchhistory'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='dispatchconfiguration',
            name='cancellation_rate_weight',
        ),
        migrations.AddField(
            model_name='delivery',
            name='destination_address',
            field=models.TextField(default='12, Alaba Int Market, Ojo, Lagos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='destination_latitude',
            field=models.DecimalField(decimal_places=6, default=66.5, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='destination_longitude',
            field=models.DecimalField(decimal_places=6, default=66.5, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='package_size',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='delivery',
            name='package_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='pickup_address',
            field=models.TextField(default='46, Ajao Estate, Lagos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='pickup_latitude',
            field=models.DecimalField(decimal_places=6, default=66.5, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='pickup_longitude',
            field=models.DecimalField(decimal_places=6, default=66.5, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('BIKE', 'Bike'), ('CAR', 'Car'), ('VAN', 'Van')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='vendor',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='vendors.vendorprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispatchconfiguration',
            name='cancellation_weight',
            field=models.DecimalField(decimal_places=2, default=8, help_text='Penalty applied to riders with higher cancellation rates.', max_digits=6),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('WAITING_FOR_RIDER', 'Waiting for Rider'), ('RIDER_ASSIGNED', 'Rider Assigned'), ('RIDER_ACCEPTED', 'Rider Accepted'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='deliveryassignment',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='deliveries.delivery'),
        ),
        migrations.AlterField(
            model_name='deliveryassignment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('ACCEPTED', 'Accepted'), ('EN_ROUTE_PICKUP', 'En Route to Pickup'), ('ARRIVED_PICKUP', 'Arrived at Pickup'), ('PICKED_UP', 'Picked Up'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('ARRIVED_DESTINATION', 'Arrived at Destination'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='deliveryoffer',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deliveryoffer',
            name='search_radius',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='deliveryoffer',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='dispatchconfiguration',
            name='dispatch_strategy',
            field=models.CharField(choices=[('BALANCED', 'Balanced'), ('NEAREST', 'Nearest Rider'), ('PERFORMANCE', 'Performance Based'), ('VENDOR_PRIORITY', 'Vendor Priority'), ('CUSTOMER_PRIORITY', 'Customer Priority'), ('FAIR_DISTRIBUTION', 'Fair Distribution'), ('EXPRESS', 'Express Delivery')], default='BALANCED', help_text='Determines how riders are ranked during dispatch.', max_length=30),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['status'], name='deliveries__status_bdfe1b_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['payment_status'], name='deliveries__payment_570175_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['vendor'], name='deliveries__vendor__a7b338_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['customer'], name='deliveries__custome_2e03f8_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryassignment',
            index=models.Index(fields=['delivery', 'status'], name='deliveries__deliver_08f50c_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryassignment',
            index=models.Index(fields=['rider', 'status'], name='deliveries__rider_i_a07fbe_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryassignment',
            index=models.Index(fields=['is_active'], name='deliveries__is_acti_b50520_idx'),
        ),
    ]
