# Generated by Django 6.0.6 on 2026-08-29 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0007_alter_dispatchconfiguration_max_rider_assignments'),
        ('order', '0002_packageitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='fulfillment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='delivery', to='order.orderfulfillment'),
        ),
    ]
