# Generated by Django 6.0.6 on 2026-09-09 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0008_alter_delivery_fulfillment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='deliveryassignment',
            name='unique_active_delivery_assignment',
        ),
        migrations.RenameIndex(
            model_name='deliveryassignment',
            new_name='assignment_delivery_status_idx',
            old_name='deliveries__deliver_08f50c_idx',
        ),
        migrations.RenameIndex(
            model_name='deliveryassignment',
            new_name='assignment_rider_status_idx',
            old_name='deliveries__rider_i_a07fbe_idx',
        ),
        migrations.RenameIndex(
            model_name='deliveryassignment',
            new_name='assignment_rider_active_idx',
            old_name='deliveries__rider_i_842e2c_idx',
        ),
        migrations.RenameIndex(
            model_name='deliveryassignment',
            new_name='assignment_status_idx',
            old_name='deliveries__status_648496_idx',
        ),
        migrations.RenameIndex(
            model_name='deliveryassignment',
            new_name='assignment_active_idx',
            old_name='deliveries__is_acti_b50520_idx',
        ),
        migrations.RenameIndex(
            model_name='deliveryassignment',
            new_name='assignment_assigned_at_idx',
            old_name='deliveries__assigne_e971eb_idx',
        ),
        migrations.AlterField(
            model_name='deliveryassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='Admin/staff/system user that created the assignment. Null means system-generated.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_delivery_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deliveryassignment',
            name='delivery',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='assignment', to='deliveries.delivery'),
        ),
        migrations.AlterField(
            model_name='dispatchconfiguration',
            name='max_rider_assignments',
            field=models.PositiveSmallIntegerField(default=0, help_text='Maximum number of rider assignments allowed for a delivery. Use 0 for unlimited.'),
        ),
        migrations.AddConstraint(
            model_name='deliveryassignment',
            constraint=models.UniqueConstraint(fields=('delivery',), name='unique_delivery_assignment'),
        ),
    ]
