# Generated by Django 6.0.6 on 2026-08-24 11:57

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0008_alter_delivery_options_and_more'),
        ('vendors', '0002_productcategory_product_productimage_productvariant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=255)),
                ('variant_name', models.CharField(blank=True, max_length=255)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('unit_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='delivery',
            name='pickup_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='vendors.vendorstore'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='pickup_store_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['pickup_store'], name='deliveries__pickup__1f8af0_idx'),
        ),
        migrations.AddField(
            model_name='deliveryitem',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='deliveries.delivery'),
        ),
        migrations.AddField(
            model_name='deliveryitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_items', to='vendors.product'),
        ),
        migrations.AddField(
            model_name='deliveryitem',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_items', to='vendors.vendorstore'),
        ),
        migrations.AddField(
            model_name='deliveryitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_items', to='vendors.productvariant'),
        ),
        migrations.AddIndex(
            model_name='deliveryitem',
            index=models.Index(fields=['delivery'], name='deliveries__deliver_78ca5a_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryitem',
            index=models.Index(fields=['product'], name='deliveries__product_73fc9b_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryitem',
            index=models.Index(fields=['variant'], name='deliveries__variant_041ee5_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryitem',
            index=models.Index(fields=['store'], name='deliveries__store_i_c32f44_idx'),
        ),
    ]
