# Generated by Django 6.0.6 on 2026-09-09 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0009_remove_deliveryassignment_unique_active_delivery_assignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryassignment',
            name='delivery',
            field=models.OneToOneField(help_text='The single lifetime assignment for this delivery.', on_delete=django.db.models.deletion.PROTECT, related_name='assignment', to='deliveries.delivery'),
        ),
    ]
