# Generated by Django 6.0.6 on 2026-10-04 08:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0010_alter_deliveryassignment_delivery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='deliveryassignment',
            name='unique_delivery_assignment',
        ),
        migrations.RenameIndex(
            model_name='deliveryoffer',
            new_name='offer_delivery_status_idx',
            old_name='deliveries__deliver_56f416_idx',
        ),
        migrations.RenameIndex(
            model_name='deliveryoffer',
            new_name='offer_rider_status_idx',
            old_name='deliveries__rider_i_96c255_idx',
        ),
        migrations.RenameIndex(
            model_name='deliveryoffer',
            new_name='offer_expires_at_idx',
            old_name='deliveries__expires_b7811a_idx',
        ),
        migrations.AddField(
            model_name='delivery',
            name='package_size',
            field=models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large')], default='SMALL', help_text='Package size bucket used for pricing. One of SMALL / MEDIUM / LARGE.', max_length=10),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('BIKE', 'Bike'), ('CAR', 'Car'), ('VAN', 'Van'), ('TRUCK', 'Truck')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryoffer',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddConstraint(
            model_name='deliveryoffer',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('delivery', 'rider'), name='unique_pending_offer_per_delivery_rider'),
        ),
    ]
