# Generated by Django 6.0.6 on 2026-10-07 18:19

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0011_remove_deliveryassignment_unique_delivery_assignment_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='deliveryaddress',
            name='deliveries__deliver_30402e_idx',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='pickup_store_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))]),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))]),
        ),
        migrations.AlterField(
            model_name='deliveryitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='deliveryitem',
            name='sku',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='deliveryitem',
            name='total_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryitem',
            name='unit_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryitem',
            name='variant_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='dispatchhistory',
            name='status',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
