# Generated by Django 6.0.6 on 2026-10-09 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0012_remove_deliveryaddress_deliveries__deliver_30402e_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatchconfiguration',
            name='max_rider_assignments',
        ),
    ]
